version: '3.9'
services:
  nginx:
    image: nginx:alpine-slim
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - nginx-network

networks: 
  mongo-network:
    name: mongo-network
    driver: bridge

  nginx-network:
    name: nginx-network
    driver: bridge

  mysql-network:
    name: mysql-network
    driver: bridge
    
  